algoritmo "Nome do Programa"

var
produto : vetor [1..4] de caractere 
opcao : inteiro 

inicio
produtos[1] <- "Alface" 
produtos[2] <- "PS5"
produtos[3] <- "Mandioca"
produtos[4] <- "Beterraba"

escreval ("Qual o codigo do produto?")
leia(produto)
se (produtos [opcao] <> underfined) entao   
    escreval("Opção invalida ou nao cadastrada!")
senao 
    escreval("Produto : "+produtos[opcao])
fimSe





fimalgoritmo