algoritmo "DJ LANCHES" 

inicio
escreval ("**** Catálogo ****")
escreval ("a: X-tudo - R$10,50")
escreval ("b: bacon-cheddar - R$ 15,90")
escreval ("c: milksahke - R$ 17,00") 
escreval ("d: cancelar")

leia(opcao)
// switch / case 
escolha(opcao)
    caso ("a")
        escreval("x-tudo adicionado!")
    caso ("b")
    escreval ("bacon-cheddar adicionado!")
    caso ("c") 
    escreval("Milkshake adicionado!")
outrocaso 
    escreval("Opção iválida!")
fimEscolha 
fimalgoritmo